- name: Configure webserver on the server instance
  hosts: appserver
  connection: ssh
  become: true

  # vars:
  #   docker_network_name: "{{ docker_network_name }}"  # This will use the value from inventory.yml

  tasks:
    # Ensure network exists first
    - name: Ensure Docker network exists
      docker_network:
        name: "appnetwork"
        state: present
        driver: bridge
        attachable: yes

    # Create and Setup Nginx
    - name: Copy nginx config files
      copy:
        src: "./nginx-conf/nginx"
        dest: "/conf"
    - name: Create nginx container
      docker_container:
        name: "nginx"
        image: "nginx:stable"
        state: started
        recreate: yes
        published_ports:
          - 80:80
          - 443:443
        networks:
          - name: "appnetwork"
        volumes:
          - /conf/nginx/nginx.conf:/etc/nginx/nginx.conf

    - name: "Restart nginx container"
      shell: "docker container restart nginx"